# Generated by Django 6.1.1 on 2026-09-06 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='DepartureCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resort', models.CharField(blank=True, max_length=150)),
                ('stars', models.PositiveSmallIntegerField(blank=True, choices=[(3, '3*'), (4, '4*'), (5, '5*')], null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='Tour.country')),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Tour.hotel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('nights', models.PositiveSmallIntegerField()),
                ('adults_count', models.PositiveSmallIntegerField(default=2)),
                ('children_count', models.PositiveSmallIntegerField(default=0)),
                ('meal_type', models.CharField(choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Сніданок і вечеря'), ('FB', 'Повний пансіон'), ('AI', 'Все включено'), ('UAI', 'Ультра все включено')], max_length=3)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(choices=[('UAH', 'грн'), ('USD', '$'), ('EUR', '€')], default='UAH', max_length=3)),
                ('is_hot', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('sold_out', 'Мест нет'), ('expired', 'Не актуален')], default='active', max_length=10)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_created', to=settings.AUTH_USER_MODEL)),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.departurecity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.hotel')),
                ('tour_operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.touroperator')),
            ],
            options={
                'ordering': ['-is_hot', 'departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='Tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='Tour.tour')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['hotel', 'departure_date'], name='Tour_tour_hotel_i_d65eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_hot', 'status'], name='Tour_tour_is_hot_af9ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price_amount'], name='Tour_tour_price_a_a7a379_idx'),
        ),
    ]
