# Generated by Django 6.1.1 on 2026-09-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='Tour.country'),
        ),
        migrations.AddField(
            model_name='hotelphoto',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Tour.hotel'),
        ),
        migrations.AddField(
            model_name='tour',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.departurecity'),
        ),
        migrations.AddField(
            model_name='tour',
            name='goal_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.goalcity'),
        ),
        migrations.AddField(
            model_name='tour',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='Tour.tour'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='Tour.tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.touroperator'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['hotel', 'departure_date'], name='Tour_tour_hotel_i_d65eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_hot', 'status'], name='Tour_tour_is_hot_af9ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price_amount'], name='Tour_tour_price_a_a7a379_idx'),
        ),
    ]
