# Generated by Django 6.1.1 on 2026-09-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='children_count',
            new_name='children',
        ),
    ]
