# Generated by Django 6.1.1 on 2026-09-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_cities', to='Tour.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='goal_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='Tour.goalcity'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='Tour.country'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='goal_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.goalcity'),
        ),
    ]
