# Generated by Django 6.1.1 on 2026-09-08 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_goalcity_country_hotel_goal_city_alter_hotel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='Tour.touroperator'),
        ),
    ]
