# Generated by Django 6.1.1 on 2026-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0003_rename_children_count_tour_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
