# Generated by Django 6.1.1 on 2026-09-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0004_alter_tour_tour_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
