# Generated by Django 6.1.1 on 2026-09-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0004_tour_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
    ]
