# Generated by Django 6.1.1 on 2026-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0005_remove_tour_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
