# Generated by Django 6.1.1 on 2026-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0006_bookingrequest_preferred_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='adults_count',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='meal_type',
            field=models.CharField(choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Сніданок і вечеря'), ('FB', 'Повний пансіон'), ('AI', 'Все включено'), ('UAI', 'Ультра все включено')], default='RO', max_length=3),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
