# Generated by Django 6.1.1 on 2026-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0007_bookingrequest_adults_count_bookingrequest_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='preferred_contact',
            field=models.CharField(choices=[('viber', 'Viber'), ('telegram', 'Telegram')], default='telegram', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('RO', 'Без харчування'), ('BB', 'Сніданок'), ('HB', 'Сніданок і вечеря'), ('FB', 'Повний пансіон'), ('AI', 'Все включено'), ('UAI', 'Ультра все включено')], max_length=3),
        ),
    ]
