# Generated by Django 6.1.1 on 2026-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0008_bookingrequest_preferred_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Показувати цей відгук у блоці «Про турагента» на головній (макс. 3)'),
        ),
    ]
