# Generated by Django 6.1.1 on 2026-09-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0010_bookingrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
