# Generated by Django 6.1.1 on 2026-09-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour', '0011_review_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('confirmed', 'Підтверджена'), ('cancelled', 'Відмінена')], default='new', max_length=15),
        ),
    ]
